# Generated by Django 4.2.7 on 2025-06-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExternalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_recipients', to='email_app.email')),
            ],
        ),
    ]
