import os

print("Email Configuration Setup")
print("=" * 30)
print()

print("For Gmail, you'll need to:")
print("1. Enable 2-factor authentication on your Google account")
print("2. Generate an App Password (not your regular password)")
print("3. Use the App Password in the EMAIL_HOST_PASSWORD setting")
print()

print("Common SMTP Settings:")
print()
print("Gmail:")
print("  EMAIL_HOST=smtp.gmail.com")
print("  EMAIL_PORT=587")
print("  EMAIL_USE_TLS=True")
print()
print("Outlook/Hotmail:")
print("  EMAIL_HOST=smtp-mail.outlook.com")
print("  EMAIL_PORT=587")
print("  EMAIL_USE_TLS=True")
print()
print("Yahoo:")
print("  EMAIL_HOST=smtp.mail.yahoo.com")
print("  EMAIL_PORT=587")
print("  EMAIL_USE_TLS=True")
print()

print("Create a .env file in your project root with:")
print("EMAIL_HOST=smtp.gmail.com")
print("EMAIL_PORT=587")
print("EMAIL_USE_TLS=True")
print("EMAIL_HOST_USER=your-email@gmail.com")
print("EMAIL_HOST_PASSWORD=your-app-password")
print("DEFAULT_FROM_EMAIL=your-email@gmail.com")
print()

print("For Gmail App Password:")
print("1. Go to https://myaccount.google.com/")
print("2. Security > 2-Step Verification > App passwords")
print("3. Generate a new app password")
print("4. Use this 16-character password (not your regular password)")
